<a href="https://colab.research.google.com/github/Kavikarthik14/Data-with-python/blob/main/My_progress_Interrogating_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Interrogating the dataframe
---

We use pandas to create dataframes from data sets in files or online tables.

Once we have the dataframe we might want to:  
*   display a subset of rows
*   *   we can do this using df.head(), df.tail() or df.iloc[index]
*   display a subset of columns
*   *   we can do this using the column name as the key, e.g.   
`                df['rain (mm)']`  
*   *   we can display more than one column, simply by listing the columns in the square brackets, e.g.   
`                df[['rain (mm)', 'tmin (degC)', 'sun (hours)']]`  
*   *   and can dislay a subset of rows for a subset of columns, e.g.  
 `               df[['rain (mm)', 'tmax (degC)']].head(10)`

### Exercise 1 - get the data, look at first 10 records
---


1.  Import the pandas library with the alias pd  
2.  Read the sheet with the name "Industry Migration" from the Excel file from this link: https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true  (*Hint:  use pd.read_excel(url, sheet_name="Industry Migration") with the above url.*)
3.  display the first 10 rows of the data

In [ ]:
import pandas as pd
from google.colab import files
#uploaded= files.upload()
df = pd.read_excel("public_use-talent-migration.xlsx", sheet_name ="Industry Migration")
display(df.head(10))

,country_code,country_name,wb_income,wb_region,isic_section_index,isic_section_name,industry_id,industry_name,net_per_10K_2015,net_per_10K_2016,net_per_10K_2017,net_per_10K_2018,net_per_10K_2019
0,ae,United Arab Emirates,High income,Middle East & North Africa,C,Manufacturing,1,Defense & Space,378.74,127.94,8.20,68.51,49.55
1,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,3,Computer Hardware,100.97,358.14,112.98,149.57,182.22
2,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,4,Computer Software,1079.36,848.15,596.48,409.18,407.41
3,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,5,Computer Networking,401.46,447.39,163.99,236.69,188.07
4,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,6,Internet,1840.33,1368.42,877.71,852.39,519.40
5,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,8,Telecommunications,676.91,676.11,365.96,283.59,281.91
6,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,9,Law Practice,694.50,529.50,362.83,356.56,147.83
7,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,10,Legal Services,661.10,665.65,462.30,475.62,255.21
8,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,11,Management Consulting,982.85,694.25,520.28,574.60,406.03
9,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,12,Biotechnology,1230.17,846.28,500.77,205.78,513.23

### Exercise 2 - display just two columns

Display the first 50 records focusing on the industries where migration is happening in each country (show just country_name and industry_name).

In [ ]:
import pandas as pd
from google.colab import files
#uploaded =  files.upload()
df = pd.read_excel("public_use-talent-migration (2).xlsx", sheet_name = "Industry Migration")
df[['country_name', 'industry_name']].head(51)

            country_name              industry_name
0   United Arab Emirates            Defense & Space
1   United Arab Emirates          Computer Hardware
2   United Arab Emirates          Computer Software
3   United Arab Emirates        Computer Networking
4   United Arab Emirates                   Internet
5   United Arab Emirates         Telecommunications
6   United Arab Emirates               Law Practice
7   United Arab Emirates             Legal Services
8   United Arab Emirates      Management Consulting
9   United Arab Emirates              Biotechnology
10  United Arab Emirates           Medical Practice
11  United Arab Emirates     Hospital & Health Care
12  United Arab Emirates            Pharmaceuticals
13  United Arab Emirates             Medical Device
14  United Arab Emirates                  Cosmetics
15  United Arab Emirates          Apparel & Fashion
16  United Arab Emirates             Sporting Goods
17  United Arab Emirates                    Tobacco
18  United Arab Emirates               Supermarkets
19  United Arab Emirates            Food Production
20  United Arab Emirates       Consumer Electronics
21  United Arab Emirates             Consumer Goods
22  United Arab Emirates                  Furniture
23  United Arab Emirates                     Retail
24  United Arab Emirates              Entertainment
25  United Arab Emirates  Leisure, Travel & Tourism
26  United Arab Emirates                Hospitality
27  United Arab Emirates                Restaurants
28  United Arab Emirates                     Sports
29  United Arab Emirates           Food & Beverages
30  United Arab Emirates     Motion Pictures & Film
31  United Arab Emirates            Broadcast Media
32  United Arab Emirates                    Banking
33  United Arab Emirates                  Insurance
34  United Arab Emirates         Financial Services
35  United Arab Emirates                Real Estate
36  United Arab Emirates         Investment Banking
37  United Arab Emirates      Investment Management
38  United Arab Emirates                 Accounting
39  United Arab Emirates               Construction
40  United Arab Emirates         Building Materials
41  United Arab Emirates    Architecture & Planning
42  United Arab Emirates          Civil Engineering
43  United Arab Emirates       Aviation & Aerospace
44  United Arab Emirates                 Automotive
45  United Arab Emirates                  Chemicals
46  United Arab Emirates                  Machinery
47  United Arab Emirates            Mining & Metals
48  United Arab Emirates               Oil & Energy
49  United Arab Emirates               Shipbuilding
50  United Arab Emirates                  Utilities

### Exercise 3 - yearly migration

*   display the middle 20 records, showing the country_name and the migration for each of the years 2015 to 2019.
---

In [ ]:
from pandas._libs.tslibs.offsets import YearBegin
from pandas.core.algorithms import unique
import pandas as pd
from google.colab import files
#uploaded = files.upload()
df= pd.read_excel("public_use-talent-migration.xlsx", sheet_name= "Industry Migration")
middle_index = len(df) //2
middle_records = df.iloc[middle_index-10 : middle_index+10]
print(middle_records)

     country_code country_name            wb_income  \
2637           in        India  Lower middle income
2638           in        India  Lower middle income
2639           in        India  Lower middle income
2640           in        India  Lower middle income
2641           in        India  Lower middle income
2642           in        India  Lower middle income
2643           in        India  Lower middle income
2644           in        India  Lower middle income
2645           in        India  Lower middle income
2646           in        India  Lower middle income
2647           in        India  Lower middle income
2648           in        India  Lower middle income
2649           in        India  Lower middle income
2650           in        India  Lower middle income
2651           in        India  Lower middle income
2652           in        India  Lower middle income
2653           iq         Iraq  Upper middle income
2654           iq         Iraq  Upper middle income
2655           iq         Iraq  Upper middle income
2656           iq         Iraq  Upper middle income

                       wb_region isic_section_index  \
2637                  South Asia                  P
2638                  South Asia                  G
2639                  South Asia                  H
2640                  South Asia                  M
2641                  South Asia                  M
2642                  South Asia                  N
2643                  South Asia                  N
2644                  South Asia                  M
2645                  South Asia                  S
2646                  South Asia                  G
2647                  South Asia                  G
2648                  South Asia                  C
2649                  South Asia                  C
2650                  South Asia                  C
2651                  South Asia                  C
2652                  South Asia                  O
2653  Middle East & North Africa                  C
2654  Middle East & North Africa                  J
2655  Middle East & North Africa                  G
2656  Middle East & North Africa                  I

                                      isic_section_name  industry_id  \
2637                                          Education          132
2638  Wholesale and retail trade; repair of motor ve...          133
2639                         Transportation and storage          134
2640   Professional scientific and technical activities          135
2641   Professional scientific and technical activities          136
2642      Administrative and support service activities          137
2643      Administrative and support service activities          138
2644   Professional scientific and technical activities          140
2645                           Other service activities          141
2646  Wholesale and retail trade; repair of motor ve...          142
2647  Wholesale and retail trade; repair of motor ve...          143
2648                                      Manufacturing          144
2649                                      Manufacturing          145
2650                                      Manufacturing          146
2651                                      Manufacturing          147
2652  Public administration and defence; compulsory ...          148
2653                                      Manufacturing            1
2654                      Information and communication            8
2655  Wholesale and retail trade; repair of motor ve...           27
2656          Accommodation and food service activities           31

                             industry_name  net_per_10K_2015  \
2637                            E-Learning             -7.57
2638                             Wholesale            -46.07
2639                       Import & Export            -17.75
2640  Mechanical or Industrial Engineering            -46.50
2641                           Photography             15.19
2642                       Human Resources            -36.77
2643         Business Supplies & Equipment            -57.53
2644                        Graphic Design              4.31
2645     International Trade & Development            -60.63
2646                        Wine & Spirits            -26.63
2647                Luxury Goods & Jewelry            -31.78
2648              Renewables & Environment             24.01
2649            Glass, Ceramics & Concrete            -17.74
2650                Packaging & Containers            -26.23
2651                 Industrial Automation            -75.42
2652                  Government Relations            -40.41
2653                       Defense & Space            290.14
2654                    Telecommunications             23.68
2655                                Retail           -138.81
2656                           Hospitality           -718.56

      net_per_10K_2016  net_per_10K_2017  net_per_10K_2018  net_per_10K_2019
2637            -15.53            -41.39            -58.19            -75.65
2638            -84.82            -69.27           -112.88           -102.83
2639             -9.88            -13.85            -17.02            -36.78
2640            -53.41            -38.84            -69.76            -73.81
2641              5.91            -67.67            -42.27            -45.82
2642            -72.50           -224.30           -108.44            -57.46
2643            -50.04            -58.67            -98.15            -87.12
2644            -29.11            -68.60            -60.27            -71.01
2645           -102.39           -130.02            -97.02           -151.55
2646              5.22            -29.57            -23.96            -58.40
2647            -45.04            -86.56            -66.87            -95.41
2648             27.84             -9.85            -29.43            -63.83
2649            -27.67            -19.57            -63.91            -50.87
2650            -21.12            -26.23            -40.06            -55.07
2651            -71.15            -57.01            -95.02           -106.56
2652             -2.47            -40.18            -70.58           -142.21
2653            396.01            175.95            396.23            318.73
2654           -148.03           -157.05            -87.85            -38.84
2655           -662.75           -273.35           -109.23              0.00
2656           -623.25           -446.93           -456.94             95.72

### Exercise 4 - migration to and from
---

The Excel file at this link (which you have already opened above): https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true has three data sheets, "Country Migration", "Industry Migration" and "Skills Migration"

Open the data sheet "Country Migration" and display the first 10 records showing the country that migration was to, the country it was from and the net migration for each year from 2015 to 2019

In [ ]:
import pandas as pd
from google.colab import files
#uploaded = files.upload()
df = pd.read_excel('public_use-talent-migration.xlsx', sheet_name ='Country Migration')
required_column=['target_country_name', 'base_country_name', 'net_per_10K_2015','net_per_10K_2016','net_per_10K_2017','net_per_10K_2018','net_per_10K_2019']
first_10_records = df[required_column].head(10)
print(first_10_records)

Saving public_use-talent-migration.xlsx to public_use-talent-migration.xlsx
  target_country_name     base_country_name  net_per_10K_2015  \
0         Afghanistan  United Arab Emirates              0.19
1             Algeria  United Arab Emirates              0.19
2              Angola  United Arab Emirates             -0.01
3           Argentina  United Arab Emirates              0.16
4             Armenia  United Arab Emirates              0.10
5           Australia  United Arab Emirates             -1.06
6             Austria  United Arab Emirates              0.11
7          Azerbaijan  United Arab Emirates              0.24
8             Bahrain  United Arab Emirates              0.90
9          Bangladesh  United Arab Emirates             -0.21

   net_per_10K_2016  net_per_10K_2017  net_per_10K_2018  net_per_10K_2019
0              0.16              0.11             -0.05             -0.02
1              0.25              0.57              0.55              0.78
2              0.04              0.11             -0.02             -0.06
3              0.18              0.04              0.01              0.23
4              0.05              0.03             -0.01              0.02
5             -3.31             -4.01             -4.58             -4.09
6             -0.08             -0.07             -0.05             -0.16
7              0.25              0.10              0.05              0.04
8              0.89              0.38             -0.07              0.15
9             -0.21             -0.26             -0.18             -0.04

# New Section

# New Section

### Exercise 5 - unique countries

Using the "Country Migration" sheet, get all the unique country names from where people have migrated (base_country_name) and use a for loop to print a list of the countries.

In [ ]:
df= pd.read_excel("public_use-talent-migration.xlsx", sheet_name= "Country Migration")
df['base_country_name'].unique()
for country in df['base_country_name'].unique() :
  print(country)

United Arab Emirates
Afghanistan
Albania
Armenia
Angola
Argentina
Austria
Australia
Azerbaijan
Bosnia and Herzegovina
Bangladesh
Belgium
Burkina Faso
Bulgaria
Bahrain
Benin
Bolivia
Brazil
Bahamas, The
Botswana
Belarus
Canada
Congo, Dem. Rep.
Switzerland
Cote d'Ivoire
Chile
Cameroon
China
Colombia
Costa Rica
Cuba
Cyprus
Czech Republic
Germany
Denmark
Dominican Republic
Algeria
Ecuador
Estonia
Egypt, Arab Rep.
Spain
Ethiopia
Finland
Fiji
France
Gabon
United Kingdom
Georgia
Ghana
Greece
Guatemala
Hong Kong SAR, China
Honduras
Croatia
Haiti
Hungary
Indonesia
Ireland
Israel
India
Iraq
Iran, Islamic Rep.
Iceland
Italy
Jamaica
Jordan
Japan
Kenya
Cambodia
Korea, Rep.
Kuwait
Kazakhstan
Lebanon
Sri Lanka
Lithuania
Luxembourg
Latvia
Libya
Morocco
Moldova
Madagascar
Macedonia, FYR
Mali
Myanmar
Mongolia
Malta
Mauritius
Malawi
Mexico
Malaysia
Mozambique
Namibia
Nigeria
Nicaragua
Netherlands
Norway
Nepal
New Zealand
Oman
Panama
Peru
Papua New Guinea
Philippines
Pakistan
Poland
Puerto Rico
West Bank and Gaza
Portugal
Paraguay
Qatar
Romania
Serbia
Rwanda
Saudi Arabia
Sudan
Sweden
Singapore
Slovenia
Slovak Republic
Senegal
El Salvador
Syrian Arab Republic
Togo
Thailand
Tunisia
Turkey
Trinidad and Tobago
Taiwan, China
Tanzania
Ukraine
Uganda
United States
Uruguay
Uzbekistan
Venezuela, RB
Vietnam
Yemen, Rep.
South Africa
Zambia
Zimbabwe

### Exercise 6 - how many countries are migrated to

Using the "Country Migration" sheet again, get all the unique country names to where people have migrated and display the number of unique countries.

In [ ]:
df= pd.read_excel("public_use-talent-migration.xlsx", sheet_name= "Country Migration")
unique_countries = df['target_country_name'].unique()
num_unique_countries= len(unique_countries)
print("Enter number of Unique countries:" , num_unique_countries)

Enter number of Unique countries: 140

### Exercise 7 - skill sets
---


Using the "Skill Migration" data sheet, display the following:
*  the first record
*  the last 10 records
*  records from index 500 to index 600  
*  a count of all unique countries
*  a list of all unique skill group categories
*  the first 50 rows, skill group names and net migration in 2019 only

In [ ]:
df= pd.read_excel("public_use-talent-migration.xlsx" , sheet_name = "Skill Migration")
display(df.head(1))
display(df.tail(10))
display(df.iloc[500:601])
unique_countries=df['country_name'].unique()
num_unique_countries= len(unique_countries)
print("count of all Unique countries:" , num_unique_countries)
df['skill_group_category'].unique()
df[['skill_group_name',  'net_per_10K_2019' ]].head(51)

,country_code,country_name,wb_income,wb_region,skill_group_id,skill_group_category,skill_group_name,net_per_10K_2015,net_per_10K_2016,net_per_10K_2017,net_per_10K_2018,net_per_10K_2019
0,af,Afghanistan,Low income,South Asia,2549,Tech Skills,Information Management,-791.59,-705.88,-550.04,-680.92,-1208.79

,country_code,country_name,wb_income,wb_region,skill_group_id,skill_group_category,skill_group_name,net_per_10K_2015,net_per_10K_2016,net_per_10K_2017,net_per_10K_2018,net_per_10K_2019
17607,zw,Zimbabwe,Low income,Sub-Saharan Africa,5587,Specialized Industry Skills,Earth Science,7.00,-5.61,-48.68,-71.76,-111.85
17608,zw,Zimbabwe,Low income,Sub-Saharan Africa,1838,Specialized Industry Skills,Utilities,-157.50,-170.89,-81.63,-139.70,-110.54
17609,zw,Zimbabwe,Low income,Sub-Saharan Africa,3104,Specialized Industry Skills,International Law,-98.23,-72.38,-94.81,-128.64,-105.16
17610,zw,Zimbabwe,Low income,Sub-Saharan Africa,1530,Specialized Industry Skills,Higher Education,54.17,-3.69,-18.88,11.91,-96.81
17611,zw,Zimbabwe,Low income,Sub-Saharan Africa,25045,Specialized Industry Skills,Agricultural Production,-127.75,-56.95,5.54,-42.07,-95.85
17612,zw,Zimbabwe,Low income,Sub-Saharan Africa,12666,Specialized Industry Skills,Teaching,71.18,30.68,-18.85,-68.89,-93.70
17613,zw,Zimbabwe,Low income,Sub-Saharan Africa,1235,Specialized Industry Skills,Mining,8.97,-112.85,-35.87,-65.38,-93.46
17614,zw,Zimbabwe,Low income,Sub-Saharan Africa,43756,Specialized Industry Skills,Personal Coaching,-53.45,-59.70,-88.01,-55.90,-82.23
17615,zw,Zimbabwe,Low income,Sub-Saharan Africa,1724,Specialized Industry Skills,Public Health,15.25,-65.53,-57.22,-39.39,-32.14
17616,zw,Zimbabwe,Low income,Sub-Saharan Africa,172,Specialized Industry Skills,Law,40.85,47.16,-31.24,-8.24,-25.52

,country_code,country_name,wb_income,wb_region,skill_group_id,skill_group_category,skill_group_name,net_per_10K_2015,net_per_10K_2016,net_per_10K_2017,net_per_10K_2018,net_per_10K_2019
500,ar,Argentina,High income,Latin America & Caribbean,26209,Tech Skills,Digital Literacy,-8.46,1.60,38.82,57.56,-53.18
501,ar,Argentina,High income,Latin America & Caribbean,12666,Specialized Industry Skills,Teaching,-14.33,-26.96,9.16,13.86,-52.78
502,ar,Argentina,High income,Latin America & Caribbean,42956,Specialized Industry Skills,Delivery Operations,-44.05,-43.48,2.46,-67.62,-50.99
503,ar,Argentina,High income,Latin America & Caribbean,2269,Business Skills,Project Management,-34.32,38.07,94.94,135.19,-50.02
504,ar,Argentina,High income,Latin America & Caribbean,2597,Business Skills,Business Management,-15.28,10.38,54.07,70.10,-49.83
...,...,...,...,...,...,...,...,...,...,...,...,...
596,au,Australia,High income,East Asia & Pacific,4382,Business Skills,Debt Collection,6.71,2.17,45.03,7.91,22.41
597,au,Australia,High income,East Asia & Pacific,1235,Specialized Industry Skills,Mining,-63.59,-32.71,10.68,14.54,23.75
598,au,Australia,High income,East Asia & Pacific,43756,Specialized Industry Skills,Personal Coaching,4.36,23.71,37.86,31.71,25.18
599,au,Australia,High income,East Asia & Pacific,1275,Specialized Industry Skills,Property Management,-5.45,13.10,12.72,19.49,25.82
600,au,Australia,High income,East Asia & Pacific,11891,Specialized Industry Skills,Religious Studies,2.88,36.42,19.74,6.16,26.79

count of all Unique countries: 140

                          skill_group_name  net_per_10K_2019
0                   Information Management          -1208.79
1                   Operational Efficiency           -790.09
2                        National Security           -767.64
3                         Software Testing           -739.51
4                                     Navy           -718.64
5                        Materials Science           -717.73
6                             Criminal Law           -698.84
7                          Problem Solving           -696.16
8   Software Development Life Cycle (SDLC)           -692.24
9                            Cybersecurity           -640.96
10                     Enterprise Software           -625.19
11                       Water Engineering           -560.86
12                               Air Force           -553.91
13                           Documentation           -534.90
14                           Public Safety           -531.68
15                       People Management           -489.62
16                               Economics           -481.75
17               Administrative Assistance           -481.00
18                      Telecommunications           -470.25
19                   Management Consulting           -465.04
20                   Aerospace Engineering           -459.57
21                Environmental Consulting           -456.65
22                                Politics           -455.72
23                    Human Resources (HR)           -454.04
24                                     Law           -444.72
25                       Personal Coaching           -442.94
26                           Public Policy           -432.87
27                                 Writing           -429.40
28                        Payroll Services           -417.59
29                        Accounts Payable           -415.60
30                             Translation           -409.63
31                Corporate Communications           -407.53
32                             Bookkeeping           -406.50
33                       Technical Support           -405.87
34               Data Storage Technologies           -402.25
35                     Computer Networking           -401.17
36                         Social Services           -400.00
37                             Procurement           -381.75
38                Construction Engineering           -380.71
39                             Electronics           -379.37
40                        Entrepreneurship           -375.82
41                   System Administration           -375.25
42                Manufacturing Operations           -369.78
43                   Environmental Science           -369.71
44                       Growth Strategies           -364.60
45                    Nonprofit Management           -356.44
46         Employee Learning & Development           -353.67
47                               Machining           -347.71
48                              Recruiting           -339.42
49                      Emergency Medicine           -332.85
50                 Food Service Operations           -332.41

### Exercise 8 - total net migration over 5 years
---

Using the Country Migration data sheet, display the record at position 10.  Using the column names to access the data in each column, add the five columns containing the net migration data together to calculate the total net migration over the 5 years between 2015 and 2019.

In [ ]:
df = pd.read_excel("public_use-talent-migration.xlsx", sheet_name= "Country Migration")
display(df.iloc[11])
columns_to_sum = ['net_per_10K_2015','net_per_10K_2016','net_per_10K_2017','net_per_10K_2018','net_per_10K_2015']
total_net_migration = df.loc[11,columns_to_sum].sum()
print('Total Net Migration:', total_net_migration)

base_country_code                                   ae
base_country_name                 United Arab Emirates
base_lat                                     23.424076
base_long                                    53.847818
base_country_wb_income                     High Income
base_country_wb_region      Middle East & North Africa
target_country_code                                 be
target_country_name                            Belgium
target_lat                                   50.503887
target_long                                   4.469936
target_country_wb_income                   High Income
target_country_wb_region         Europe & Central Asia
net_per_10K_2015                                  0.51
net_per_10K_2016                                  0.22
net_per_10K_2017                                 -0.01
net_per_10K_2018                                 -0.09
net_per_10K_2019                                 -0.06
Name: 11, dtype: object

Total Net Migration: 1.1400000000000001

### Exercise 9 - formulating a text response

Using the Industry Migration data sheet, display the record at position 100.  Using the column names again to access the data in each column, calculate net migration over the 5 years from 2015 to 2019.

Then print the following message, adding the data where indicated:

The total net migration into `country` of skilled workers for the `industry name` industry, during the years 2015-2019 was `total_net_migration`

In [ ]:
import pandas as pd
from google.colab import files
#uploaded = files.upload()
df= pd.read_excel('public_use-talent-migration.xlsx', sheet_name = 'Industry Migration')
r_99= df.iloc[50]
net_migration = sum([r_99['net_per_10K_2015'],r_99['net_per_10K_2016'],r_99['net_per_10K_2017'],r_99['net_per_10K_2018'],r_99['net_per_10K_2019']])
country=r_99['country_name']
industry=r_99['industry_name']
print('The total net migration into', country, 'of skilled workers for the',industry, ",", 'during the years 2015-2019 was' , net_migration  )

The total net migration into United Arab Emirates of skilled workers for the Utilities , during the years 2015-2019 was 1426.7400000000002

### Exercise 10 - five text responses

Using the Industry Migration data sheet, calculate net migration (rounded to 1 decimal place) over the 5 years from 2015 to 2019 for the records at positions 1 to 5 and print the following message for each, adding the data where indicated:

The total net migration into `country` of skilled workers for the `industry name` industry, during the years 2015-2019 was `total_net_migration`

*Hint: use a for loop to get a record and do each calculation*

In [ ]:
import pandas as pd
url=('https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true')
df= pd.read_excel('public_use-talent-migration.xlsx', sheet_name = 'Industry Migration')
for i in range (0,5) :
  record=df.iloc[i]
  net_migration = round(sum([record['net_per_10K_2015'],record['net_per_10K_2016'],record['net_per_10K_2017'],record['net_per_10K_2018'],record['net_per_10K_2019']]),1)
  country= record['country_name']
  industry= record['industry_name']
  print('The total net migration into', country, 'of skilled workers for the',industry, ",", 'during the years 2015-2019 was' , net_migration  )

The total net migration into United Arab Emirates of skilled workers for the Defense & Space , during the years 2015-2019 was 632.9
The total net migration into United Arab Emirates of skilled workers for the Computer Hardware , during the years 2015-2019 was 903.9
The total net migration into United Arab Emirates of skilled workers for the Computer Software , during the years 2015-2019 was 3340.6
The total net migration into United Arab Emirates of skilled workers for the Computer Networking , during the years 2015-2019 was 1437.6
The total net migration into United Arab Emirates of skilled workers for the Internet , during the years 2015-2019 was 5458.2